/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class DiscoveryTest {
//    @Test public void testSomeLibraryMethod() {
//        Discovery classUnderTest = new Discovery();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
}
